#!/bin/bash
#
# Copyright (C) 2017 Richard Mortier <mort@cantab.net>.  All Rights
# Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
# USA.

set -e
## debug
if [[ "$FIXER_DEBUG" = "true" ]]; then
  set -x
  PS4='$LINENO: '
fi

## constants
FIXER=https://api.fixer.io

## defaults
BASE=GBP
SYMBOLS=USD,EUR
DATE=$(date +%Y-%m-%d)

usage () {
  echo "Request exchange rate between BASE currency and a list"
  echo "  of target currency SYMBOLs on a given DATE"
  echo "Usage: $0 [-b|--base=BASE] [-s|--symbols=SYMBOLS] DATE"
  echo "  -b|--base[=]BASE       set the base currency ($BASE)"
  echo "  -s|--symobls[=]SYMBOLS comma-separated list of target currencies ($SYMBOLS)"
  echo "DATE format is yyyy-mm-dd ($DATE)"
}

ARGS=
while [[ $# > 0 ]]; do
  OPTIND=1
  while getopts -- "b:s:-:h" optchar; do
    case "$optchar" in
      b)
        BASE="$2"
        shift 2
        break
        ;;

      s)
        SYMBOLS="$2"
        shift 2
        break
        ;;

      -)
        case "$OPTARG" in
          base)
            BASE="$2"
            shift 2
            break
            ;;
          base=*)
            BASE="${OPTARG#*=}"
            shift
            break
            ;;

          symbols)
            SYMBOLS="$2"
            shift 2
            break
            ;;
          symbols=*)
            SYMBOLS="${OPTARG#*=}"
            shift
            break
            ;;

          help)
            usage
            exit 0
            ;;

          *)
            usage
            exit 1
            ;;
        esac
        break
        ;;

      *)
        usage
        exit 1
        ;;
    esac
  done
  while [[ $# > 0 && ${1:0:1} != "-" ]]; do
    ARGS="$ARGS $1"
    shift
  done
done

set -- $ARGS
[[ $# > 0 ]] && DATE=$1 || true

curl -s "$FIXER/$DATE?base=$BASE&symbols=$SYMBOLS" \
  | docker run -i mor1/jq .rates
