#!/bin/bash
#
# Copy data from phone
#
# Copyright (C) 2016-2019 Richard Mortier <mort@cantab.net>.  All Rights
# Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
# USA.

set -e
if [[ "$RSYNC_PHONE_DEBUG" = "true" ]]; then
  set -x
fi

## PHOTOS
D=~/me/photos/incoming/nexus5x

mkdir -p $D
pushd $D

T=$(mktemp -d "${TMPDIR:-/tmp}"rsync-adb.XXXXXX)
function onexit {
  echo rm -rf "$T"
}
trap onexit EXIT

## get incoming files
adb shell ls -l /sdcard/DCIM/Camera/ | tr -s " " | cut -f 5,8 -d" " \
  | sort -t" " -k 2 | uniq | grep '^[[:digit:]].*\.\(mp4\|jpg\)$' >| $T/remote

## fix up list of already imported files
ls -l [IPV]* | grep -v IMPORTED | tr -s " " | cut -d " " -f 5,9 >> IMPORTED
cat IMPORTED \
  | sort -t" " -k 2 | uniq | grep '^[[:digit:]].*\.\(mp4\|jpg\)$' >| $T/local

## compare local and remote, and copy any missing or too small
for f in $(diff -u $T/local $T/remote | grep "^+[^+]" | cut -d" " -f 2) ; do
  echo == $f
  adb pull -p -a /sdcard/DCIM/Camera/$f .
done

find . -type f | xargs chmod 644

mv IMPORTED IMPORTED.old
cp $T/local IMPORTED
popd

pushd ~/me/footprint/weightmeter
adb pull -p -a /sdcard/Download/weightmeter .
popd
